var fr1=[""];
    var fr2=["😘 Bonjour,","🥰 Salut les gars!","💦 Bonjour,","👙 Comment faites-vous?","🔞 Hé,","😜 Salut.","🥴 Yo!","👙 Howdy!","💦 G’day mate!","🔞 Hiya!","💦 Hé, qu’est-ce qui se passe?","💦 Hé, toi !","🥰 Salut les garçons!"]
var us1=["Contact me here","Other private Information About Me","Come Talk to Me on My private Profile","private Chat and call me or find me","Waiting for a private partner 👄 Lets get contact me","Contact  here! 📩 Lets get private","Click here for the live private","See more my private photo and video","Check out the preview of my latest video","I need a date, Find and private Call Me","If you are looking for me, contact me here! all private"];
    var us2=["😘 Hello,","🥰 Hi guys!","💦 Hi there,","👙 How do you do?","🔞 Hey,","😜 Hey there.","🥴 Yo!","👙 Howdy!","💦 G'day mate!","🔞 Hiya!","💦 Hey, what's up?","💦 Hey, you!","🥰 Hi boys!"]
var it1=[""];
    var it2=["😘 Ciao,","🥰 Ciao ragazzi!","💦 Ciao,","👙 Come si fa?","🔞 Ehi,","😜 Ehi, ecco.","🥴 Yo!","👙 Howdy!","💦 compagno G'day!","🔞 Hiya!","💦 Ehi, che succede?","💦 Ehi, tu!","🥰 Ciao ragazzi!"]
var jp1=["こちらからご連絡ください","その他の個人情報について","私のプライベートプロフィールで私に話しに来て","プライベートチャットと私を呼び出すか、私を見つける","プライベートパートナーを待っている👄私に連絡しましょう","お問い合わせはこちら!📩 プライベートにしましょう","ライブプライベートについては、ここをクリックしてください","私のプライベート写真とビデオをもっと見る","最新のビデオのプレビューをチェック","私は日付、検索とプライベートコールミーが必要です","あなたが私を探しているなら、ここで私に連絡してください!すべてのプライベート"];    
    var jp2=["😘、こんにちは","🥰 こんにちはみんな!","💦 こんにちは、","👙 どうする?","🔞 ねえ、","😜 おい","🥴ヨ!","👙ハウディ!","💦G'dayメイト!","🔞ヒヤ!","💦 おい どうしたの?","💦 おい、お前!","🥰こんにちは男の子!"]
var de1=[""];
    var de2=["😘 Hallo,","🥰 Hallo Leute!","💦 Hallo,","👙 Wie machen Sie das?","🔞 Hey,","😜 Hallo.","🥴 Yo!","👙 Howdy!","💦 G'day Mate!","🔞 Hiya!","💦 Hey, was ist los?","💦 Hey, du!","🥰 Hallo Jungs!"]
var kr1=[""];
    var kr2=["😘 안녕하세요,","안녕 얘들 아 🥰!","💦 안녕,","👙 어떻게 해야 하나요?","🔞 이봐,","😜 이봐.","🥴 요!","👙 하우디!","💦 G'day 친구!","🔞 히야!","💦 이봐, 무슨 일이야?","💦 이봐, 당신!","🥰 안녕 소년!"]
var tw1=[""];
    var tw2=["😘你好，","嗨， 伙计们🥰！","💦你好，","👙 你怎么做？","🔞嘿","😜嘿","🥴哟！","👙豪迪！","💦 G 'day 伴侣！","🔞希亚！","💦嘿，怎么了？","💦嘿，你！","嗨， 孩子们🥰！"]
var br1=[""];
    var br2=["😘 Olá,","🥰 oi pessoal!","💦 Oi lá,","👙 Como você faz?","🔞 Ei,","😜 Ei aí.","🥴 Yo!","👙 Howdy!","💦 companheiro do G'day!","🔞 Hiya!","💦 Ei, e aí?","💦 Ei, você!","🥰 rapazes do Oi!"]
var tr1=[""];
    var tr2=["😘 Merhaba,","🥰 Merhaba çocuklar!","💦 Merhaba,","👙 Nasılsın?","🔞 Merhaba,","😜 Merhaba.","🥴 Yo!","👙 Howdy!","💦 G'day dostum!","Hiya'yı 🔞!","💦 merhaba, ne oldu?","💦 Hey, sen!","🥰 Merhaba çocuklar!"]
var pl1=["Skontaktuj się ze mną tutaj","Inne prywatne informacje o mnie","Przyjdź porozmawiać ze mną na moim prywatnym profilu","prywatny czat i zadzwoń do mnie lub znajdź mnie","Czekając na partnera prywatnego 👄 Skontaktuj się ze mną","Skontaktuj się ze mną"," Skontaktuj się tutaj! 📩 Lets get private","Kliknij tutaj, aby zobaczyć prywatne na żywo","Zobacz więcej moich prywatnych zdjęć i filmów","Sprawdź podgląd mojego najnowszego filmu","Potrzebuję daty, Znajdź i prywatnie Zadzwoń do mnie","Jeśli mnie szukasz, skontaktuj się ze mną tutaj! wszystkie prywatne"];
    var pl2=["😘 Cześć,","🥰 Cześć chłopaki!","💦 Cześć tam,","👙 Jak to robisz?","🔞 Hej,","😜 Hej tam.","🥴 Yo!","👙 Howdy!","💦 G'day mate!","🔞 Hiya!","💦 Hej, co tam jest?","💦 Hej, ty!","🥰 Cześć chłopcy!"]
	
var tanda1=["💞 ","💕 ","💋 ","💟 ","🥀 ","🌺 ","🌹 ","🌸 ","🌷 "]
var tanda2=[" ⬇👇"]
var tanda3=["🤑","👻","😸","😹","💀","🤠","🥴","🤮","🤢","😈","☠","😻","😼","👽","👿","🤮","🤧","👹","👾","😽","🙀","🤖","👺","🤡","😷","🤒","🤕","🤡","🎃","😿","😾","😺","💩","🌷","🌹","🥀","🌺","🌸","🌼","🌻","🌞","💐","🌾","🐚","🍁","🍂","🍃","🎋","🍀","☘","🌿","🌱","🌴","🌳","🌲","💦","💧","💎","✧☾","✨","🦁","🌶","💥","🎼","💫","⚜","❄️","💙","👑","🎵","🔥","💋","🦅","🧸"]
var tanda4=["男、私はあなたが欲しい"]
var tanda5=["mec, je te veux"]
var tanda6=["Mann, ich will dich"]
var tanda7=["Men, i need you"]
var tanda8=["男人，我想你"]
var tanda9=["uomo, ti voglio"]
var tanda10=["남자, 난 당신이 필요해"]
var tanda11=["Homens, eu preciso de vocês"]
var tanda12=["Beyler, size ihtiyacım var"]
var tanda13=["Mężczyźni, potrzebuję was"]
